create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, id bigint not null, end_date date not null, start_date date not null, primary key (employee_email, id)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, total_vacation_days integer not null, year varchar(255) not null, primary key (employee)) engine=MyISAM;
alter table vacation_dates add constraint FKsfrq1aaw1hw1vk1t40vvx0ccg foreign key (employee_email) references vacation_days_per_years (employee);
create table vacation_dates (employee_email varchar(255) not null, start_date date not null, end_date date not null, primary key (employee_email, start_date)) engine=MyISAM;
create table vacation_days_per_years (employee varchar(255) not null, year varchar(255) not null, total_vacation_days integer not null, primary key (employee, year)) engine=MyISAM;
